/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_abemu_free: (a: number, b: number) => void;
export const abemu_cpuType: (a: number) => number;
export const abemu_eepromDirty: (a: number) => number;
export const abemu_frame: (a: number) => [number, number];
export const abemu_gifRecording: (a: number) => number;
export const abemu_gifStart: (a: number) => void;
export const abemu_gifStop: (a: number) => [number, number];
export const abemu_ledRgb: (a: number) => [number, number];
export const abemu_ledRx: (a: number) => number;
export const abemu_ledTx: (a: number) => number;
export const abemu_loadEeprom: (a: number, b: number, c: number) => void;
export const abemu_loadFile: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const abemu_loadFx: (a: number, b: number, c: number) => void;
export const abemu_loadState: (a: number, b: number, c: number) => [number, number];
export const abemu_new: () => number;
export const abemu_renderAudio: (a: number, b: number, c: number) => [number, number];
export const abemu_reset: (a: number) => void;
export const abemu_runFrame: (a: number) => void;
export const abemu_saveEeprom: (a: number) => [number, number];
export const abemu_saveState: (a: number) => [number, number, number, number];
export const abemu_screenHeight: () => number;
export const abemu_screenWidth: () => number;
export const abemu_setButton: (a: number, b: number, c: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
